# -*- coding: utf-8 -*-
"""Learn PySpark

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzUPRsP5Y9vm3IDRm9Q-QEPJzzalFbtt
"""

import pyspark
from pyspark.sql import SparkSession

"""Membuat Spark Session"""

spark = SparkSession \
    .builder \
    .appName("Learn PySpark Data Pipeline") \
    .getOrCreate()
spark

df_rdd = spark.sparkContext\
            .parallelize([(1, 2, 3, 'a b c'),
                          (4, 5, 6, 'd e f'),
                          (7, 8, 9, 'g h i')])\
            .toDF(['col_1', 'col_2', 'col_3', 'col_4'])

df_rdd.show()

"""Pandas vs PySpark"""

import pandas as pd
import time

"""Menggunakan Pandas"""

# compare speed

def read_big_table_pandas(filename: str):
  start_time = time.time()

  df = pd.read_csv(filename)

  end_time = time.time()

  elapsed_time = end_time - start_time

  return elapsed_time, df

elapsed_time, df_pandas = read_big_table_pandas(filename = "flights_big_data.csv")
print(f'Time to read CSV: {elapsed_time} scond')

# Melihat isi tabel Pandas

df_pandas.head()

"""Menggunakan PySpark"""

def read_big_table_pyspark(filename: str):
  start_time = time.time()

  df = spark \
      .read \
      .option('header', 'true')\
      .csv(filename)

  end_time = time.time()

  elapsed_time = end_time - start_time

  return elapsed_time, df

elapsed_time, df_pyspark = read_big_table_pyspark(filename = "flights_big_data.csv")
print(f'Time to read CSV: {elapsed_time} seconds')

# Melihat isi tabel PySpark

df_pyspark.show(5)

"""Read data using PySpark"""

# Membaca data flights_big_data.csv

df_flights = spark \
            .read \
            .option('header', 'true') \
            .csv('flights_big_data.csv')

# show the data
df_flights.show()

"""Export data into CSV file use PySpark"""

# Menentukan kolom yang akan disimpan di file csv
selected_cols = ["AIRLINE", "FLIGHT_NUMBER", "ORIGIN_AIRPORT",
                 "DESTINATION_AIRPORT","DAY", "MONTH", "YEAR"]

new_df_flights = df_flights.select(selected_cols)

new_df_flights.show()

# Filter kolom destination_airport dan kolom month
filtered_df_flights =  new_df_flights.filter("DESTINATION_AIRPORT == 'LAX' AND MONTH == 12")

filtered_df_flights.show()

# Menyimpan data yang sudah diolah dan difilter
new_df_flights.coalesce(numPartitions = 1).write.csv("filtered_data_single", header = True)

# Menyimpan data menjadi partisi
new_df_flights.write.option('header', True).csv('filtered_data_partition')

"""Select & Filter Using PySpark"""

# Membaca data flights_big_data
df_flights = spark \
            .read \
            .option('header', 'true') \
            .csv('flights_big_data.csv')

df_flights.show(5)

# Menentukan kolom yang akan dipilih
selected_cols = ["AIRLINE", "FLIGHT_NUMBER", "ORIGIN_AIRPORT", "DESTINATION_AIRPORT", "SCHEDULED_DEPARTURE",
                 "DEPARTURE_TIME", "ARRIVAL_TIME", "DAY", "MONTH", "YEAR"]

selected_df_flights = df_flights.select(selected_cols)

selected_df_flights.show(5)

# Filter data using PySpark based
filtered_df = selected_df_flights.filter(selected_df_flights['AIRLINE'] == "NK")

# Filter data using SQL based
filtered_df_sql = selected_df_flights.filter("AIRLINE = 'NK'")

filtered_df_sql.show(5)

"""Menggunakan Multiple Filter"""

# Multiple Filter using PySpark Base
filtered_df = selected_df_flights.filter((selected_df_flights['MONTH'] > 5) & (selected_df_flights['ORIGIN_AIRPORT'] == 'LAX'))

# Multiple Filter using SQL Base
filtered_df_sql = selected_df_flights.filter("MONTH > 5 AND ORIGIN_AIRPORT = 'LAX'")

filtered_df_sql.show(5)

"""Export data using PySpark"""

# Menenukan kolom yang akan disimpan
selected_cols = ["AIRLINE", "FLIGHT_NUMBER", "ORIGIN_AIRPORT",
                 "DESTINATION_AIRPORT","DAY", "MONTH", "YEAR"]

new_df_flights = df_flights.select(selected_cols)

new_df_flights.show()

# Filter data yang akan dimasukan
filtered_df_flights = new_df_flights.filter((new_df_flights['DESTINATION_AIRPORT'] == 'LAX') & (new_df_flights['MONTH'] == 12))

filtered_df_flights.show()

# Menyimpan data yang sudah difilter
new_df_flights.coalesce(numPartitions = 1).write.csv("filtered_data_single", header = True)